### ISSUE TITLE
ValueError: range() arg 3 must not be zero

### ISSUE THREAD

**Issue by xiangyupan** [bodegalab/irescue#1]
Hi,
Thanks for the nice job in bioRxiv, hope it will be successfully accepted in a good journal.
Now I want to use it to quantificate my single-cell RNA-seq data.
An error occurred when I ran the command 
`  nohup ~/anaconda3/envs/irescue/bin/irescue -b possorted_genome_bam.bam -p 8 -r /public1/home/sc60481/Axolotl/sc-RNA/03.deal.TE/All.TE.deal.bed -w ./filtered_feature_bc_matrix/barcodes.tsv.gz &
`. I am not sure what caused the error. 
Hope for your reply and help.

Thanks for your time and work.

![图片](https://user-images.githubusercontent.com/20773767/192975956-91e12436-b03d-438f-8369-f9bc5f8c676b.png)

**Comment by bepoli** [comment]
Hi @xiangyupan, thank you for your interest in IRescue.

Could you check if the files `IRescue_out/barcodes.tsv.gz` and `IRescue_out/barcodes.tsv.gz` are empty?
Please, copy and paste here the output of `zcat barcodes.tsv.gz | head | cat -et` and `zcat barcodes.tsv.gz | head | cat -et`.

Cheers
B

**Comment by xiangyupan** [comment]
Hi bepoli,
Thanks for your fast response!
Yes ,the IRescue_out/barcodes.tsv.gz  and IRescue_out/features.tsv.gz files are empty. And the matrix.tsv.gz file is not generated.
![图片](https://user-images.githubusercontent.com/20773767/193000908-b325eeb9-4b30-48d9-968f-f70f51d9ce5d.png)

**Comment by bepoli** [comment]
Ok, this narrows down the problem.

One reason could be that bedtools and/or samtools are not in your user's PATH.
Please try `bedtools --version` and `samtools --version` to make sure you have them installed.

I noticed that you executed IRescue from `~/anaconda3/envs/irescue/bin/irescue`. Did you actually activated the conda environment? If not, activate it with `conda activate irescue` and then run the analysis again.

**Comment by xiangyupan** [comment]
Thanks for your reply.
I make sure that bedtools and samtools are both in my PATH just as follows.
![图片](https://user-images.githubusercontent.com/20773767/193003404-d67fc361-c17a-455c-a5f9-42c2ddc14fe8.png)
Now I will try the second suggestion, as my bam file is huge (71Gb), I will feedback my results a little late.
Thanks again!

**Comment by bepoli** [comment]
> Now I will try the second suggestion, as my bam file is huge (71Gb), I will feedback my results a little late. Thanks again!

Please, when you run irescue, add the options `-v` and `--keep-tmp`, so we can troubleshoot better.

**Comment by xiangyupan** [comment]
Hi bepoli,
Fowllowing your suggestions, I reran the irescue yesterday, but the same error occurred.
The latese command is ` nohup irescue -b possorted_genome_bam.bam -p 8 -r /public1/home/sc60481/Axolotl/sc-RNA/03.deal.TE/All.TE.deal.bed -w ./filtered_feature_bc_matrix/barcodes.tsv.gz -v --keeptmp  &`.
And the log file contains some process infomation as follows.
It seems that no other errors during the mapping or intersecting process, but the ./IRescue_out//barcodes.tsv.gz and ./IRescue_out//features.tsv.gz files are still empty.
Do you need other files to troubleshoot this error? 
Thanks for your help.

![图片](https://user-images.githubusercontent.com/20773767/193174586-39b2c048-1ae4-45f6-9d1d-82bb245f7178.png)

**Comment by bepoli** [comment]
Hi @xiangyupan ,
now we should be able to find the problem.

- I notice the names of the chromosomes in your bed file. Do they match those in your BAM? Could you please send me a `head` of your BED and BAM file?
- Now you should have a `IRescue_tmp` directory. Inside you will find two directories `refs` and `isec`. Please check if the files in each directory are empty (you can just check one file inside `refs` and one file inside `isec`). If they are not empty, send me a `head` of each file.

**Comment by xiangyupan** [comment]
Hi, 
Sorry for the delayed response. I have checked my bed file and Bam file, the chromosomes are identical. The 'C0XXX' IDs are scaffold of the axolotl genome.
I randomly select 100  transposable elements and write it into "All.TE.deal.random100.bed.txt" file.
And the "dp0.bam.header.txt" file is the header infomation of the single-cell RNA-seq bam.
I have the IRescue_tmp directory and the head info of files in refs (chr9q4.bed.gz) and isec (chr9q4.isec.bed.gz) are also as follows.
Thanks for your time.

[All.TE.deal.random100.bed.txt](https://github.com/bodegalab/irescue/files/9738258/All.TE.deal.random100.bed.txt)
[dp0.bam.header.txt](https://github.com/bodegalab/irescue/files/9738259/dp0.bam.header.txt)
[chr9q4.bed.gz](https://github.com/bodegalab/irescue/files/9738260/chr9q4.bed.gz)
[chr9q4.isec.bed.gz](https://github.com/bodegalab/irescue/files/9738324/chr9q4.isec.bed.gz)

**Comment by bepoli** [comment]
Hi @xiangyupan,

No problem, thank you for getting back to me.

I have found and fixed two tiny bugs that could cause your problem. I think that the read names in your BAM file end with `/1`, is it the case? Also, I see that you are running the analysis at superfamily/class level, not subfamily, and this was an use case that I overlooked. Now it should work with your input BAM and BED files.

So let's try this:

- Download this archive to your server: [IRescue-1.0.1.dev5+gb83049a.tar.gz](https://github.com/bodegalab/irescue/files/9746353/IRescue-1.0.1.dev5%2Bgb83049a.tar.gz)
- In your server, **after activating your `irescue` conda environment**, run `pip install ./IRescue-1.0.1.dev5+gb83049a.tar.gz`.
- Check if the installation ran correctly by running `irescue --version`. The result should be `IRescue 1.0.1.dev5+gb83049a`.
- Try running again irescue with the same parameters as before.

If you still receive the error, then there is something else that we need to check, but at least we would rule out a couple of possible bugs.

**Comment by xiangyupan** [comment]
Thank you very much bepoli.
The update version works successfully in my job.
Now I have got the IRescue_out directory within three files now. 
IRescue_out/
├── barcodes.tsv.gz
├── features.tsv.gz
└── matrix.mtx.gz
Then I can use these to go further. Thanks again!
![图片](https://user-images.githubusercontent.com/20773767/195085029-f0be4781-3912-41bc-988e-9b3d02e762aa.png)

**Comment by bepoli** [comment]
Good!
Thank you for taking time to debug.
I just merged the fixes in version 1.0.2, which will be available in conda in a few hours.
If you need more help you can write here or open a new issue.

**Comment by mikecuoco** [comment]
Hi @bepoli. Thanks for this great method. I'm using IRescue v1.0.2 and encountering this same problem. 

1. My `IRescue_out/barcodes.tsv.gz` and `IRescue_out/features.tsv.gz` files are both empty
2. My environment has samtools 1.16 and bedtools 2.30.0
3. The chromosome names in the `rmsk.bed` file match those in my bam file

Here's the IRescue output from my run.

```
(irescue) 
mcuoco at logg-cluster-1.salk.edu in ~/workflows/scrnaseq on main*
$ irescue --bam .test/results/map_count/a/Aligned.sortedByCoord.out.bam --genome hg38 -p 4
[02/14/2023 - 19:27:27] IRescue job starts
[02/14/2023 - 19:27:27] Downloading and parsing RepeatMasker annotation for assembly hg38 from https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.out.gz...
[02/14/2023 - 19:27:48] Writing mapped barcodes to ./IRescue_out//barcodes.tsv.gz
[02/14/2023 - 19:27:48] Writing mapped features to ./IRescue_out//features.tsv.gz
Traceback (most recent call last):
  File "/raidixshare_log-g/mcuoco/miniconda3/envs/irescue/bin/irescue", line 10, in <module>
    sys.exit(main())
  File "/raidixshare_log-g/mcuoco/miniconda3/envs/irescue/lib/python3.10/site-packages/irescue/main.py", line 86, in main
    bc_per_thread = list(split_bc(barcodes_file, args.threads))
  File "/raidixshare_log-g/mcuoco/miniconda3/envs/irescue/lib/python3.10/site-packages/irescue/count.py", line 126, in split_bc
    for chunk in split_int(bclen, n):
  File "/raidixshare_log-g/mcuoco/miniconda3/envs/irescue/lib/python3.10/site-packages/irescue/count.py", line 112, in split_int
    for i in range(0, num, split):
ValueError: range() arg 3 must not be zero
```

**Comment by bepoli** [comment]
Hi @mikecuoco, thank you for the detailed report.
The `chr21.isec.bed.gz' file misses the cell barcode and UMI sequences, so I think it could be something in your BAM file that IRescue doesn't recognize yet.

Could you paste here a few lines from your BAM file?

Let's also check the integrity of the header: could you run `samtools idxstats Aligned.sortedByCoord.out.bam` and check if you obtain a 4-column text with chromosome name, length, mapped and unmapped reads?

**Comment by mikecuoco** [comment]
Hi @bepoli, thanks for the quick response! It turns out STARsolo does not include the CR and CB tags by default. I added the following line to my STARsolo and IRescue works fine now. 

```
--outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM
```

**Comment by bepoli** [comment]
Great! I'm happy to hear that!
